name: Sanity check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: python:3.12

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Run tests
      run: docker-compose up --build test

